#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clothing_Store
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Store_Fashion")]
	public partial class khdbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblQuangCao(tblQuangCao instance);
    partial void UpdatetblQuangCao(tblQuangCao instance);
    partial void DeletetblQuangCao(tblQuangCao instance);
    partial void Inserttbl_TinTuc(tbl_TinTuc instance);
    partial void Updatetbl_TinTuc(tbl_TinTuc instance);
    partial void Deletetbl_TinTuc(tbl_TinTuc instance);
    partial void Inserttbl_Quyen(tbl_Quyen instance);
    partial void Updatetbl_Quyen(tbl_Quyen instance);
    partial void Deletetbl_Quyen(tbl_Quyen instance);
    partial void Inserttbl_QuanLyMeNu(tbl_QuanLyMeNu instance);
    partial void Updatetbl_QuanLyMeNu(tbl_QuanLyMeNu instance);
    partial void Deletetbl_QuanLyMeNu(tbl_QuanLyMeNu instance);
    partial void Inserttbl_PhieuNhap(tbl_PhieuNhap instance);
    partial void Updatetbl_PhieuNhap(tbl_PhieuNhap instance);
    partial void Deletetbl_PhieuNhap(tbl_PhieuNhap instance);
    partial void Inserttbl_NhomHang(tbl_NhomHang instance);
    partial void Updatetbl_NhomHang(tbl_NhomHang instance);
    partial void Deletetbl_NhomHang(tbl_NhomHang instance);
    partial void Inserttbl_NhanVien(tbl_NhanVien instance);
    partial void Updatetbl_NhanVien(tbl_NhanVien instance);
    partial void Deletetbl_NhanVien(tbl_NhanVien instance);
    partial void Inserttbl_LienLac(tbl_LienLac instance);
    partial void Updatetbl_LienLac(tbl_LienLac instance);
    partial void Deletetbl_LienLac(tbl_LienLac instance);
    partial void Inserttbl_NhaCungCap(tbl_NhaCungCap instance);
    partial void Updatetbl_NhaCungCap(tbl_NhaCungCap instance);
    partial void Deletetbl_NhaCungCap(tbl_NhaCungCap instance);
    partial void Inserttbl_KhuyenMai(tbl_KhuyenMai instance);
    partial void Updatetbl_KhuyenMai(tbl_KhuyenMai instance);
    partial void Deletetbl_KhuyenMai(tbl_KhuyenMai instance);
    partial void Inserttbl_KhachHang(tbl_KhachHang instance);
    partial void Updatetbl_KhachHang(tbl_KhachHang instance);
    partial void Deletetbl_KhachHang(tbl_KhachHang instance);
    partial void Inserttbl_Hang(tbl_Hang instance);
    partial void Updatetbl_Hang(tbl_Hang instance);
    partial void Deletetbl_Hang(tbl_Hang instance);
    partial void Inserttbl_DatHang(tbl_DatHang instance);
    partial void Updatetbl_DatHang(tbl_DatHang instance);
    partial void Deletetbl_DatHang(tbl_DatHang instance);
    partial void Inserttbl_admin(tbl_admin instance);
    partial void Updatetbl_admin(tbl_admin instance);
    partial void Deletetbl_admin(tbl_admin instance);
    partial void Inserttbl_ChiTietDatHang(tbl_ChiTietDatHang instance);
    partial void Updatetbl_ChiTietDatHang(tbl_ChiTietDatHang instance);
    partial void Deletetbl_ChiTietDatHang(tbl_ChiTietDatHang instance);
    partial void InsertPayMeThod(PayMeThod instance);
    partial void UpdatePayMeThod(PayMeThod instance);
    partial void DeletePayMeThod(PayMeThod instance);
    partial void Insertdevvn_tinhthanhpho(devvn_tinhthanhpho instance);
    partial void Updatedevvn_tinhthanhpho(devvn_tinhthanhpho instance);
    partial void Deletedevvn_tinhthanhpho(devvn_tinhthanhpho instance);
    partial void Insertdevvn_quanhuyen(devvn_quanhuyen instance);
    partial void Updatedevvn_quanhuyen(devvn_quanhuyen instance);
    partial void Deletedevvn_quanhuyen(devvn_quanhuyen instance);
    #endregion
		
		public khdbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Store_FashionConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public khdbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public khdbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public khdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public khdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblQuangCao> tblQuangCaos
		{
			get
			{
				return this.GetTable<tblQuangCao>();
			}
		}
		
		public System.Data.Linq.Table<tbl_TinTuc> tbl_TinTucs
		{
			get
			{
				return this.GetTable<tbl_TinTuc>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Quyen> tbl_Quyens
		{
			get
			{
				return this.GetTable<tbl_Quyen>();
			}
		}
		
		public System.Data.Linq.Table<tbl_QuanLyMeNu> tbl_QuanLyMeNus
		{
			get
			{
				return this.GetTable<tbl_QuanLyMeNu>();
			}
		}
		
		public System.Data.Linq.Table<tbl_PhieuNhap> tbl_PhieuNhaps
		{
			get
			{
				return this.GetTable<tbl_PhieuNhap>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhomHang> tbl_NhomHangs
		{
			get
			{
				return this.GetTable<tbl_NhomHang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhanVien> tbl_NhanViens
		{
			get
			{
				return this.GetTable<tbl_NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tbl_LienLac> tbl_LienLacs
		{
			get
			{
				return this.GetTable<tbl_LienLac>();
			}
		}
		
		public System.Data.Linq.Table<tbl_NhaCungCap> tbl_NhaCungCaps
		{
			get
			{
				return this.GetTable<tbl_NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<tbl_KhuyenMai> tbl_KhuyenMais
		{
			get
			{
				return this.GetTable<tbl_KhuyenMai>();
			}
		}
		
		public System.Data.Linq.Table<tbl_KhachHang> tbl_KhachHangs
		{
			get
			{
				return this.GetTable<tbl_KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Hang> tbl_Hangs
		{
			get
			{
				return this.GetTable<tbl_Hang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DatHang> tbl_DatHangs
		{
			get
			{
				return this.GetTable<tbl_DatHang>();
			}
		}
		
		public System.Data.Linq.Table<tbl_admin> tbl_admins
		{
			get
			{
				return this.GetTable<tbl_admin>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ChiTietDatHang> tbl_ChiTietDatHangs
		{
			get
			{
				return this.GetTable<tbl_ChiTietDatHang>();
			}
		}
		
		public System.Data.Linq.Table<PayMeThod> PayMeThods
		{
			get
			{
				return this.GetTable<PayMeThod>();
			}
		}
		
		public System.Data.Linq.Table<devvn_tinhthanhpho> devvn_tinhthanhphos
		{
			get
			{
				return this.GetTable<devvn_tinhthanhpho>();
			}
		}
		
		public System.Data.Linq.Table<devvn_quanhuyen> devvn_quanhuyens
		{
			get
			{
				return this.GetTable<devvn_quanhuyen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblQuangCao")]
	public partial class tblQuangCao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _urlImage;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<int> _Count_Click;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnurlImageChanging(string value);
    partial void OnurlImageChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnCount_ClickChanging(System.Nullable<int> value);
    partial void OnCount_ClickChanged();
    #endregion
		
		public tblQuangCao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImage", DbType="VarChar(50)")]
		public string urlImage
		{
			get
			{
				return this._urlImage;
			}
			set
			{
				if ((this._urlImage != value))
				{
					this.OnurlImageChanging(value);
					this.SendPropertyChanging();
					this._urlImage = value;
					this.SendPropertyChanged("urlImage");
					this.OnurlImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count_Click", DbType="Int")]
		public System.Nullable<int> Count_Click
		{
			get
			{
				return this._Count_Click;
			}
			set
			{
				if ((this._Count_Click != value))
				{
					this.OnCount_ClickChanging(value);
					this.SendPropertyChanging();
					this._Count_Click = value;
					this.SendPropertyChanged("Count_Click");
					this.OnCount_ClickChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_TinTuc")]
	public partial class tbl_TinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tieuDe;
		
		private string _tomtat;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngayviet;
		
		private System.Nullable<int> _id_nhanvien;
		
		private string _urlHinhAnh;
		
		private System.Nullable<int> _LuotXem;
		
		private System.Nullable<bool> _Active;
		
		private EntityRef<tbl_NhanVien> _tbl_NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntieuDeChanging(string value);
    partial void OntieuDeChanged();
    partial void OntomtatChanging(string value);
    partial void OntomtatChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnngayvietChanging(System.Nullable<System.DateTime> value);
    partial void OnngayvietChanged();
    partial void Onid_nhanvienChanging(System.Nullable<int> value);
    partial void Onid_nhanvienChanged();
    partial void OnurlHinhAnhChanging(string value);
    partial void OnurlHinhAnhChanged();
    partial void OnLuotXemChanging(System.Nullable<int> value);
    partial void OnLuotXemChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public tbl_TinTuc()
		{
			this._tbl_NhanVien = default(EntityRef<tbl_NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieuDe", DbType="NVarChar(MAX)")]
		public string tieuDe
		{
			get
			{
				return this._tieuDe;
			}
			set
			{
				if ((this._tieuDe != value))
				{
					this.OntieuDeChanging(value);
					this.SendPropertyChanging();
					this._tieuDe = value;
					this.SendPropertyChanged("tieuDe");
					this.OntieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tomtat", DbType="NVarChar(MAX)")]
		public string tomtat
		{
			get
			{
				return this._tomtat;
			}
			set
			{
				if ((this._tomtat != value))
				{
					this.OntomtatChanging(value);
					this.SendPropertyChanging();
					this._tomtat = value;
					this.SendPropertyChanged("tomtat");
					this.OntomtatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayviet", DbType="Date")]
		public System.Nullable<System.DateTime> ngayviet
		{
			get
			{
				return this._ngayviet;
			}
			set
			{
				if ((this._ngayviet != value))
				{
					this.OnngayvietChanging(value);
					this.SendPropertyChanging();
					this._ngayviet = value;
					this.SendPropertyChanged("ngayviet");
					this.OnngayvietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien", DbType="Int")]
		public System.Nullable<int> id_nhanvien
		{
			get
			{
				return this._id_nhanvien;
			}
			set
			{
				if ((this._id_nhanvien != value))
				{
					if (this._tbl_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien = value;
					this.SendPropertyChanged("id_nhanvien");
					this.Onid_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlHinhAnh", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string urlHinhAnh
		{
			get
			{
				return this._urlHinhAnh;
			}
			set
			{
				if ((this._urlHinhAnh != value))
				{
					this.OnurlHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._urlHinhAnh = value;
					this.SendPropertyChanged("urlHinhAnh");
					this.OnurlHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
		public System.Nullable<int> LuotXem
		{
			get
			{
				return this._LuotXem;
			}
			set
			{
				if ((this._LuotXem != value))
				{
					this.OnLuotXemChanging(value);
					this.SendPropertyChanging();
					this._LuotXem = value;
					this.SendPropertyChanged("LuotXem");
					this.OnLuotXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhanVien_tbl_TinTuc", Storage="_tbl_NhanVien", ThisKey="id_nhanvien", OtherKey="id", IsForeignKey=true)]
		public tbl_NhanVien tbl_NhanVien
		{
			get
			{
				return this._tbl_NhanVien.Entity;
			}
			set
			{
				tbl_NhanVien previousValue = this._tbl_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NhanVien.Entity = null;
						previousValue.tbl_TinTucs.Remove(this);
					}
					this._tbl_NhanVien.Entity = value;
					if ((value != null))
					{
						value.tbl_TinTucs.Add(this);
						this._id_nhanvien = value.id;
					}
					else
					{
						this._id_nhanvien = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Quyen")]
	public partial class tbl_Quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<int> _id_NhanVien;
		
		private string _TenQuyen;
		
		private EntitySet<tbl_NhanVien> _tbl_NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void Onid_NhanVienChanging(System.Nullable<int> value);
    partial void Onid_NhanVienChanged();
    partial void OnTenQuyenChanging(string value);
    partial void OnTenQuyenChanged();
    #endregion
		
		public tbl_Quyen()
		{
			this._tbl_NhanViens = new EntitySet<tbl_NhanVien>(new Action<tbl_NhanVien>(this.attach_tbl_NhanViens), new Action<tbl_NhanVien>(this.detach_tbl_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(50)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_NhanVien", DbType="Int")]
		public System.Nullable<int> id_NhanVien
		{
			get
			{
				return this._id_NhanVien;
			}
			set
			{
				if ((this._id_NhanVien != value))
				{
					this.Onid_NhanVienChanging(value);
					this.SendPropertyChanging();
					this._id_NhanVien = value;
					this.SendPropertyChanged("id_NhanVien");
					this.Onid_NhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyen", DbType="NVarChar(50)")]
		public string TenQuyen
		{
			get
			{
				return this._TenQuyen;
			}
			set
			{
				if ((this._TenQuyen != value))
				{
					this.OnTenQuyenChanging(value);
					this.SendPropertyChanging();
					this._TenQuyen = value;
					this.SendPropertyChanged("TenQuyen");
					this.OnTenQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Quyen_tbl_NhanVien", Storage="_tbl_NhanViens", ThisKey="id", OtherKey="id_quyen")]
		public EntitySet<tbl_NhanVien> tbl_NhanViens
		{
			get
			{
				return this._tbl_NhanViens;
			}
			set
			{
				this._tbl_NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_NhanViens(tbl_NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Quyen = this;
		}
		
		private void detach_tbl_NhanViens(tbl_NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Quyen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_QuanLyMeNu")]
	public partial class tbl_QuanLyMeNu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenMenu;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<int> _Ord;
		
		private string _Level;
		
		private string _Link;
		
		private string _TypeClick;
		
		private string _Icon;
		
		private System.Nullable<bool> _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenMenuChanging(string value);
    partial void OnTenMenuChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnOrdChanging(System.Nullable<int> value);
    partial void OnOrdChanged();
    partial void OnLevelChanging(string value);
    partial void OnLevelChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnTypeClickChanging(string value);
    partial void OnTypeClickChanged();
    partial void OnIconChanging(string value);
    partial void OnIconChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public tbl_QuanLyMeNu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMenu", DbType="NVarChar(50)")]
		public string TenMenu
		{
			get
			{
				return this._TenMenu;
			}
			set
			{
				if ((this._TenMenu != value))
				{
					this.OnTenMenuChanging(value);
					this.SendPropertyChanging();
					this._TenMenu = value;
					this.SendPropertyChanged("TenMenu");
					this.OnTenMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ord", DbType="Int")]
		public System.Nullable<int> Ord
		{
			get
			{
				return this._Ord;
			}
			set
			{
				if ((this._Ord != value))
				{
					this.OnOrdChanging(value);
					this.SendPropertyChanging();
					this._Ord = value;
					this.SendPropertyChanged("Ord");
					this.OnOrdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="NVarChar(50)")]
		public string Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(500)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeClick", DbType="NVarChar(50)")]
		public string TypeClick
		{
			get
			{
				return this._TypeClick;
			}
			set
			{
				if ((this._TypeClick != value))
				{
					this.OnTypeClickChanging(value);
					this.SendPropertyChanging();
					this._TypeClick = value;
					this.SendPropertyChanged("TypeClick");
					this.OnTypeClickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="NVarChar(250)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this.OnIconChanging(value);
					this.SendPropertyChanging();
					this._Icon = value;
					this.SendPropertyChanged("Icon");
					this.OnIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PhieuNhap")]
	public partial class tbl_PhieuNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _ngayNhap;
		
		private System.Nullable<int> _id_nhanvien;
		
		private System.Nullable<int> _id_NCC;
		
		private EntityRef<tbl_NhanVien> _tbl_NhanVien;
		
		private EntityRef<tbl_NhaCungCap> _tbl_NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnngayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnngayNhapChanged();
    partial void Onid_nhanvienChanging(System.Nullable<int> value);
    partial void Onid_nhanvienChanged();
    partial void Onid_NCCChanging(System.Nullable<int> value);
    partial void Onid_NCCChanged();
    #endregion
		
		public tbl_PhieuNhap()
		{
			this._tbl_NhanVien = default(EntityRef<tbl_NhanVien>);
			this._tbl_NhaCungCap = default(EntityRef<tbl_NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayNhap", DbType="Date")]
		public System.Nullable<System.DateTime> ngayNhap
		{
			get
			{
				return this._ngayNhap;
			}
			set
			{
				if ((this._ngayNhap != value))
				{
					this.OnngayNhapChanging(value);
					this.SendPropertyChanging();
					this._ngayNhap = value;
					this.SendPropertyChanged("ngayNhap");
					this.OnngayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien", DbType="Int")]
		public System.Nullable<int> id_nhanvien
		{
			get
			{
				return this._id_nhanvien;
			}
			set
			{
				if ((this._id_nhanvien != value))
				{
					if (this._tbl_NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien = value;
					this.SendPropertyChanged("id_nhanvien");
					this.Onid_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_NCC", DbType="Int")]
		public System.Nullable<int> id_NCC
		{
			get
			{
				return this._id_NCC;
			}
			set
			{
				if ((this._id_NCC != value))
				{
					if (this._tbl_NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_NCCChanging(value);
					this.SendPropertyChanging();
					this._id_NCC = value;
					this.SendPropertyChanged("id_NCC");
					this.Onid_NCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhanVien_tbl_PhieuNhap", Storage="_tbl_NhanVien", ThisKey="id_nhanvien", OtherKey="id", IsForeignKey=true)]
		public tbl_NhanVien tbl_NhanVien
		{
			get
			{
				return this._tbl_NhanVien.Entity;
			}
			set
			{
				tbl_NhanVien previousValue = this._tbl_NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NhanVien.Entity = null;
						previousValue.tbl_PhieuNhaps.Remove(this);
					}
					this._tbl_NhanVien.Entity = value;
					if ((value != null))
					{
						value.tbl_PhieuNhaps.Add(this);
						this._id_nhanvien = value.id;
					}
					else
					{
						this._id_nhanvien = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhaCungCap_tbl_PhieuNhap", Storage="_tbl_NhaCungCap", ThisKey="id_NCC", OtherKey="id", IsForeignKey=true)]
		public tbl_NhaCungCap tbl_NhaCungCap
		{
			get
			{
				return this._tbl_NhaCungCap.Entity;
			}
			set
			{
				tbl_NhaCungCap previousValue = this._tbl_NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._tbl_NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_NhaCungCap.Entity = null;
						previousValue.tbl_PhieuNhaps.Remove(this);
					}
					this._tbl_NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.tbl_PhieuNhaps.Add(this);
						this._id_NCC = value.id;
					}
					else
					{
						this._id_NCC = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhomHang")]
	public partial class tbl_NhomHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _TenNhomHang;
		
		private System.Nullable<bool> _Active;
		
		private string _idkhongdau;
		
		private string _khongdau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTenNhomHangChanging(string value);
    partial void OnTenNhomHangChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnidkhongdauChanging(string value);
    partial void OnidkhongdauChanged();
    partial void OnkhongdauChanging(string value);
    partial void OnkhongdauChanged();
    #endregion
		
		public tbl_NhomHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhomHang", DbType="NVarChar(50)")]
		public string TenNhomHang
		{
			get
			{
				return this._TenNhomHang;
			}
			set
			{
				if ((this._TenNhomHang != value))
				{
					this.OnTenNhomHangChanging(value);
					this.SendPropertyChanging();
					this._TenNhomHang = value;
					this.SendPropertyChanged("TenNhomHang");
					this.OnTenNhomHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idkhongdau", DbType="NVarChar(200)")]
		public string idkhongdau
		{
			get
			{
				return this._idkhongdau;
			}
			set
			{
				if ((this._idkhongdau != value))
				{
					this.OnidkhongdauChanging(value);
					this.SendPropertyChanging();
					this._idkhongdau = value;
					this.SendPropertyChanged("idkhongdau");
					this.OnidkhongdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khongdau", DbType="VarChar(200)")]
		public string khongdau
		{
			get
			{
				return this._khongdau;
			}
			set
			{
				if ((this._khongdau != value))
				{
					this.OnkhongdauChanging(value);
					this.SendPropertyChanging();
					this._khongdau = value;
					this.SendPropertyChanged("khongdau");
					this.OnkhongdauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhanVien")]
	public partial class tbl_NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tenNV;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _gioitinh;
		
		private string _ChucVu;
		
		private System.Nullable<int> _id_quyen;
		
		private string _UserName;
		
		private string _Password;
		
		private EntitySet<tbl_TinTuc> _tbl_TinTucs;
		
		private EntitySet<tbl_PhieuNhap> _tbl_PhieuNhaps;
		
		private EntityRef<tbl_Quyen> _tbl_Quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenNVChanging(string value);
    partial void OntenNVChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void Onid_quyenChanging(System.Nullable<int> value);
    partial void Onid_quyenChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public tbl_NhanVien()
		{
			this._tbl_TinTucs = new EntitySet<tbl_TinTuc>(new Action<tbl_TinTuc>(this.attach_tbl_TinTucs), new Action<tbl_TinTuc>(this.detach_tbl_TinTucs));
			this._tbl_PhieuNhaps = new EntitySet<tbl_PhieuNhap>(new Action<tbl_PhieuNhap>(this.attach_tbl_PhieuNhaps), new Action<tbl_PhieuNhap>(this.detach_tbl_PhieuNhaps));
			this._tbl_Quyen = default(EntityRef<tbl_Quyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNV", DbType="NVarChar(50)")]
		public string tenNV
		{
			get
			{
				return this._tenNV;
			}
			set
			{
				if ((this._tenNV != value))
				{
					this.OntenNVChanging(value);
					this.SendPropertyChanging();
					this._tenNV = value;
					this.SendPropertyChanged("tenNV");
					this.OntenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(50)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_quyen", DbType="Int")]
		public System.Nullable<int> id_quyen
		{
			get
			{
				return this._id_quyen;
			}
			set
			{
				if ((this._id_quyen != value))
				{
					if (this._tbl_Quyen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_quyenChanging(value);
					this.SendPropertyChanging();
					this._id_quyen = value;
					this.SendPropertyChanged("id_quyen");
					this.Onid_quyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhanVien_tbl_TinTuc", Storage="_tbl_TinTucs", ThisKey="id", OtherKey="id_nhanvien")]
		public EntitySet<tbl_TinTuc> tbl_TinTucs
		{
			get
			{
				return this._tbl_TinTucs;
			}
			set
			{
				this._tbl_TinTucs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhanVien_tbl_PhieuNhap", Storage="_tbl_PhieuNhaps", ThisKey="id", OtherKey="id_nhanvien")]
		public EntitySet<tbl_PhieuNhap> tbl_PhieuNhaps
		{
			get
			{
				return this._tbl_PhieuNhaps;
			}
			set
			{
				this._tbl_PhieuNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Quyen_tbl_NhanVien", Storage="_tbl_Quyen", ThisKey="id_quyen", OtherKey="id", IsForeignKey=true)]
		public tbl_Quyen tbl_Quyen
		{
			get
			{
				return this._tbl_Quyen.Entity;
			}
			set
			{
				tbl_Quyen previousValue = this._tbl_Quyen.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Quyen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Quyen.Entity = null;
						previousValue.tbl_NhanViens.Remove(this);
					}
					this._tbl_Quyen.Entity = value;
					if ((value != null))
					{
						value.tbl_NhanViens.Add(this);
						this._id_quyen = value.id;
					}
					else
					{
						this._id_quyen = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Quyen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_TinTucs(tbl_TinTuc entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhanVien = this;
		}
		
		private void detach_tbl_TinTucs(tbl_TinTuc entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhanVien = null;
		}
		
		private void attach_tbl_PhieuNhaps(tbl_PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhanVien = this;
		}
		
		private void detach_tbl_PhieuNhaps(tbl_PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_LienLac")]
	public partial class tbl_LienLac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ten;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _Email;
		
		private string _ChuDe;
		
		private string _NoiDung;
		
		private int _id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnChuDeChanging(string value);
    partial void OnChuDeChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public tbl_LienLac()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="Char(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuDe", DbType="NVarChar(50)")]
		public string ChuDe
		{
			get
			{
				return this._ChuDe;
			}
			set
			{
				if ((this._ChuDe != value))
				{
					this.OnChuDeChanging(value);
					this.SendPropertyChanging();
					this._ChuDe = value;
					this.SendPropertyChanged("ChuDe");
					this.OnChuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_NhaCungCap")]
	public partial class tbl_NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tenNCC;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _Email;
		
		private EntitySet<tbl_PhieuNhap> _tbl_PhieuNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenNCCChanging(string value);
    partial void OntenNCCChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public tbl_NhaCungCap()
		{
			this._tbl_PhieuNhaps = new EntitySet<tbl_PhieuNhap>(new Action<tbl_PhieuNhap>(this.attach_tbl_PhieuNhaps), new Action<tbl_PhieuNhap>(this.detach_tbl_PhieuNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNCC", DbType="NVarChar(50)")]
		public string tenNCC
		{
			get
			{
				return this._tenNCC;
			}
			set
			{
				if ((this._tenNCC != value))
				{
					this.OntenNCCChanging(value);
					this.SendPropertyChanging();
					this._tenNCC = value;
					this.SendPropertyChanged("tenNCC");
					this.OntenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NChar(10)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(10)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_NhaCungCap_tbl_PhieuNhap", Storage="_tbl_PhieuNhaps", ThisKey="id", OtherKey="id_NCC")]
		public EntitySet<tbl_PhieuNhap> tbl_PhieuNhaps
		{
			get
			{
				return this._tbl_PhieuNhaps;
			}
			set
			{
				this._tbl_PhieuNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PhieuNhaps(tbl_PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhaCungCap = this;
		}
		
		private void detach_tbl_PhieuNhaps(tbl_PhieuNhap entity)
		{
			this.SendPropertyChanging();
			entity.tbl_NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KhuyenMai")]
	public partial class tbl_KhuyenMai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _GiaTri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnGiaTriChanging(System.Nullable<int> value);
    partial void OnGiaTriChanged();
    #endregion
		
		public tbl_KhuyenMai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTri", DbType="Int")]
		public System.Nullable<int> GiaTri
		{
			get
			{
				return this._GiaTri;
			}
			set
			{
				if ((this._GiaTri != value))
				{
					this.OnGiaTriChanging(value);
					this.SendPropertyChanging();
					this._GiaTri = value;
					this.SendPropertyChanged("GiaTri");
					this.OnGiaTriChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KhachHang")]
	public partial class tbl_KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _tenKH;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _Email;
		
		private string _SDT;
		
		private string _Tinh;
		
		private string _Quan;
		
		private string _TinhTrang;
		
		private string _DiaChi;
		
		private string _Link_Fb;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenKHChanging(string value);
    partial void OntenKHChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnTinhChanging(string value);
    partial void OnTinhChanged();
    partial void OnQuanChanging(string value);
    partial void OnQuanChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnLink_FbChanging(string value);
    partial void OnLink_FbChanged();
    #endregion
		
		public tbl_KhachHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKH", DbType="NVarChar(50)")]
		public string tenKH
		{
			get
			{
				return this._tenKH;
			}
			set
			{
				if ((this._tenKH != value))
				{
					this.OntenKHChanging(value);
					this.SendPropertyChanging();
					this._tenKH = value;
					this.SendPropertyChanged("tenKH");
					this.OntenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(50)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinh", DbType="NVarChar(50)")]
		public string Tinh
		{
			get
			{
				return this._Tinh;
			}
			set
			{
				if ((this._Tinh != value))
				{
					this.OnTinhChanging(value);
					this.SendPropertyChanging();
					this._Tinh = value;
					this.SendPropertyChanged("Tinh");
					this.OnTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quan", DbType="NVarChar(50)")]
		public string Quan
		{
			get
			{
				return this._Quan;
			}
			set
			{
				if ((this._Quan != value))
				{
					this.OnQuanChanging(value);
					this.SendPropertyChanging();
					this._Quan = value;
					this.SendPropertyChanged("Quan");
					this.OnQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(50)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link_Fb", DbType="VarChar(200)")]
		public string Link_Fb
		{
			get
			{
				return this._Link_Fb;
			}
			set
			{
				if ((this._Link_Fb != value))
				{
					this.OnLink_FbChanging(value);
					this.SendPropertyChanging();
					this._Link_Fb = value;
					this.SendPropertyChanged("Link_Fb");
					this.OnLink_FbChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Hang")]
	public partial class tbl_Hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _TenHang;
		
		private string _image;
		
		private string _ChatLieu;
		
		private string _Mota;
		
		private System.Nullable<int> _LuotXem;
		
		private System.Nullable<decimal> _giaMoi;
		
		private System.Nullable<decimal> _giaCu;
		
		private System.Nullable<int> _id_Menu;
		
		private System.Nullable<int> _Soluong;
		
		private string _TinhTrang;
		
		private System.Nullable<bool> _Active;
		
		private string _image_large;
		
		private string _TomTat;
		
		private EntitySet<tbl_ChiTietDatHang> _tbl_ChiTietDatHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTenHangChanging(string value);
    partial void OnTenHangChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnChatLieuChanging(string value);
    partial void OnChatLieuChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnLuotXemChanging(System.Nullable<int> value);
    partial void OnLuotXemChanged();
    partial void OngiaMoiChanging(System.Nullable<decimal> value);
    partial void OngiaMoiChanged();
    partial void OngiaCuChanging(System.Nullable<decimal> value);
    partial void OngiaCuChanged();
    partial void Onid_MenuChanging(System.Nullable<int> value);
    partial void Onid_MenuChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void Onimage_largeChanging(string value);
    partial void Onimage_largeChanged();
    partial void OnTomTatChanging(string value);
    partial void OnTomTatChanged();
    #endregion
		
		public tbl_Hang()
		{
			this._tbl_ChiTietDatHangs = new EntitySet<tbl_ChiTietDatHang>(new Action<tbl_ChiTietDatHang>(this.attach_tbl_ChiTietDatHangs), new Action<tbl_ChiTietDatHang>(this.detach_tbl_ChiTietDatHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang", DbType="NVarChar(255)")]
		public string TenHang
		{
			get
			{
				return this._TenHang;
			}
			set
			{
				if ((this._TenHang != value))
				{
					this.OnTenHangChanging(value);
					this.SendPropertyChanging();
					this._TenHang = value;
					this.SendPropertyChanged("TenHang");
					this.OnTenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(MAX)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChatLieu", DbType="NVarChar(50)")]
		public string ChatLieu
		{
			get
			{
				return this._ChatLieu;
			}
			set
			{
				if ((this._ChatLieu != value))
				{
					this.OnChatLieuChanging(value);
					this.SendPropertyChanging();
					this._ChatLieu = value;
					this.SendPropertyChanged("ChatLieu");
					this.OnChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
		public System.Nullable<int> LuotXem
		{
			get
			{
				return this._LuotXem;
			}
			set
			{
				if ((this._LuotXem != value))
				{
					this.OnLuotXemChanging(value);
					this.SendPropertyChanging();
					this._LuotXem = value;
					this.SendPropertyChanged("LuotXem");
					this.OnLuotXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaMoi", DbType="Money")]
		public System.Nullable<decimal> giaMoi
		{
			get
			{
				return this._giaMoi;
			}
			set
			{
				if ((this._giaMoi != value))
				{
					this.OngiaMoiChanging(value);
					this.SendPropertyChanging();
					this._giaMoi = value;
					this.SendPropertyChanged("giaMoi");
					this.OngiaMoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaCu", DbType="Money")]
		public System.Nullable<decimal> giaCu
		{
			get
			{
				return this._giaCu;
			}
			set
			{
				if ((this._giaCu != value))
				{
					this.OngiaCuChanging(value);
					this.SendPropertyChanging();
					this._giaCu = value;
					this.SendPropertyChanged("giaCu");
					this.OngiaCuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_Menu", DbType="Int")]
		public System.Nullable<int> id_Menu
		{
			get
			{
				return this._id_Menu;
			}
			set
			{
				if ((this._id_Menu != value))
				{
					this.Onid_MenuChanging(value);
					this.SendPropertyChanging();
					this._id_Menu = value;
					this.SendPropertyChanged("id_Menu");
					this.Onid_MenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="NVarChar(50)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_large", DbType="VarChar(500)")]
		public string image_large
		{
			get
			{
				return this._image_large;
			}
			set
			{
				if ((this._image_large != value))
				{
					this.Onimage_largeChanging(value);
					this.SendPropertyChanging();
					this._image_large = value;
					this.SendPropertyChanged("image_large");
					this.Onimage_largeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TomTat", DbType="NVarChar(MAX)")]
		public string TomTat
		{
			get
			{
				return this._TomTat;
			}
			set
			{
				if ((this._TomTat != value))
				{
					this.OnTomTatChanging(value);
					this.SendPropertyChanging();
					this._TomTat = value;
					this.SendPropertyChanged("TomTat");
					this.OnTomTatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hang_tbl_ChiTietDatHang", Storage="_tbl_ChiTietDatHangs", ThisKey="id", OtherKey="id_hang")]
		public EntitySet<tbl_ChiTietDatHang> tbl_ChiTietDatHangs
		{
			get
			{
				return this._tbl_ChiTietDatHangs;
			}
			set
			{
				this._tbl_ChiTietDatHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_ChiTietDatHangs(tbl_ChiTietDatHang entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hang = this;
		}
		
		private void detach_tbl_ChiTietDatHangs(tbl_ChiTietDatHang entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DatHang")]
	public partial class tbl_DatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _NgaylapHD;
		
		private System.Nullable<int> _id_KhachHang;
		
		private System.Nullable<int> _IdPay;
		
		private EntitySet<tbl_ChiTietDatHang> _tbl_ChiTietDatHangs;
		
		private EntityRef<PayMeThod> _PayMeThod;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNgaylapHDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaylapHDChanged();
    partial void Onid_KhachHangChanging(System.Nullable<int> value);
    partial void Onid_KhachHangChanged();
    partial void OnIdPayChanging(System.Nullable<int> value);
    partial void OnIdPayChanged();
    #endregion
		
		public tbl_DatHang()
		{
			this._tbl_ChiTietDatHangs = new EntitySet<tbl_ChiTietDatHang>(new Action<tbl_ChiTietDatHang>(this.attach_tbl_ChiTietDatHangs), new Action<tbl_ChiTietDatHang>(this.detach_tbl_ChiTietDatHangs));
			this._PayMeThod = default(EntityRef<PayMeThod>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaylapHD", DbType="Date")]
		public System.Nullable<System.DateTime> NgaylapHD
		{
			get
			{
				return this._NgaylapHD;
			}
			set
			{
				if ((this._NgaylapHD != value))
				{
					this.OnNgaylapHDChanging(value);
					this.SendPropertyChanging();
					this._NgaylapHD = value;
					this.SendPropertyChanged("NgaylapHD");
					this.OnNgaylapHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_KhachHang", DbType="Int")]
		public System.Nullable<int> id_KhachHang
		{
			get
			{
				return this._id_KhachHang;
			}
			set
			{
				if ((this._id_KhachHang != value))
				{
					this.Onid_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._id_KhachHang = value;
					this.SendPropertyChanged("id_KhachHang");
					this.Onid_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPay", DbType="Int")]
		public System.Nullable<int> IdPay
		{
			get
			{
				return this._IdPay;
			}
			set
			{
				if ((this._IdPay != value))
				{
					if (this._PayMeThod.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPayChanging(value);
					this.SendPropertyChanging();
					this._IdPay = value;
					this.SendPropertyChanged("IdPay");
					this.OnIdPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_DatHang_tbl_ChiTietDatHang", Storage="_tbl_ChiTietDatHangs", ThisKey="id", OtherKey="id_hoadon")]
		public EntitySet<tbl_ChiTietDatHang> tbl_ChiTietDatHangs
		{
			get
			{
				return this._tbl_ChiTietDatHangs;
			}
			set
			{
				this._tbl_ChiTietDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PayMeThod_tbl_DatHang", Storage="_PayMeThod", ThisKey="IdPay", OtherKey="IdPay", IsForeignKey=true)]
		public PayMeThod PayMeThod
		{
			get
			{
				return this._PayMeThod.Entity;
			}
			set
			{
				PayMeThod previousValue = this._PayMeThod.Entity;
				if (((previousValue != value) 
							|| (this._PayMeThod.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PayMeThod.Entity = null;
						previousValue.tbl_DatHangs.Remove(this);
					}
					this._PayMeThod.Entity = value;
					if ((value != null))
					{
						value.tbl_DatHangs.Add(this);
						this._IdPay = value.IdPay;
					}
					else
					{
						this._IdPay = default(Nullable<int>);
					}
					this.SendPropertyChanged("PayMeThod");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_ChiTietDatHangs(tbl_ChiTietDatHang entity)
		{
			this.SendPropertyChanging();
			entity.tbl_DatHang = this;
		}
		
		private void detach_tbl_ChiTietDatHangs(tbl_ChiTietDatHang entity)
		{
			this.SendPropertyChanging();
			entity.tbl_DatHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_admin")]
	public partial class tbl_admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _username;
		
		private string _pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    #endregion
		
		public tbl_admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(100)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(100)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ChiTietDatHang")]
	public partial class tbl_ChiTietDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hoadon;
		
		private int _id_hang;
		
		private System.Nullable<int> _SoLuongMua;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private string _Size;
		
		private System.Nullable<decimal> _Gia;
		
		private EntityRef<tbl_Hang> _tbl_Hang;
		
		private EntityRef<tbl_DatHang> _tbl_DatHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hoadonChanging(int value);
    partial void Onid_hoadonChanged();
    partial void Onid_hangChanging(int value);
    partial void Onid_hangChanged();
    partial void OnSoLuongMuaChanging(System.Nullable<int> value);
    partial void OnSoLuongMuaChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnGiaChanging(System.Nullable<decimal> value);
    partial void OnGiaChanged();
    #endregion
		
		public tbl_ChiTietDatHang()
		{
			this._tbl_Hang = default(EntityRef<tbl_Hang>);
			this._tbl_DatHang = default(EntityRef<tbl_DatHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoadon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_hoadon
		{
			get
			{
				return this._id_hoadon;
			}
			set
			{
				if ((this._id_hoadon != value))
				{
					if (this._tbl_DatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_hoadonChanging(value);
					this.SendPropertyChanging();
					this._id_hoadon = value;
					this.SendPropertyChanged("id_hoadon");
					this.Onid_hoadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_hang
		{
			get
			{
				return this._id_hang;
			}
			set
			{
				if ((this._id_hang != value))
				{
					if (this._tbl_Hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_hangChanging(value);
					this.SendPropertyChanging();
					this._id_hang = value;
					this.SendPropertyChanged("id_hang");
					this.Onid_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongMua", DbType="Int")]
		public System.Nullable<int> SoLuongMua
		{
			get
			{
				return this._SoLuongMua;
			}
			set
			{
				if ((this._SoLuongMua != value))
				{
					this.OnSoLuongMuaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongMua = value;
					this.SendPropertyChanged("SoLuongMua");
					this.OnSoLuongMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Char(10)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Money")]
		public System.Nullable<decimal> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hang_tbl_ChiTietDatHang", Storage="_tbl_Hang", ThisKey="id_hang", OtherKey="id", IsForeignKey=true)]
		public tbl_Hang tbl_Hang
		{
			get
			{
				return this._tbl_Hang.Entity;
			}
			set
			{
				tbl_Hang previousValue = this._tbl_Hang.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hang.Entity = null;
						previousValue.tbl_ChiTietDatHangs.Remove(this);
					}
					this._tbl_Hang.Entity = value;
					if ((value != null))
					{
						value.tbl_ChiTietDatHangs.Add(this);
						this._id_hang = value.id;
					}
					else
					{
						this._id_hang = default(int);
					}
					this.SendPropertyChanged("tbl_Hang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_DatHang_tbl_ChiTietDatHang", Storage="_tbl_DatHang", ThisKey="id_hoadon", OtherKey="id", IsForeignKey=true)]
		public tbl_DatHang tbl_DatHang
		{
			get
			{
				return this._tbl_DatHang.Entity;
			}
			set
			{
				tbl_DatHang previousValue = this._tbl_DatHang.Entity;
				if (((previousValue != value) 
							|| (this._tbl_DatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_DatHang.Entity = null;
						previousValue.tbl_ChiTietDatHangs.Remove(this);
					}
					this._tbl_DatHang.Entity = value;
					if ((value != null))
					{
						value.tbl_ChiTietDatHangs.Add(this);
						this._id_hoadon = value.id;
					}
					else
					{
						this._id_hoadon = default(int);
					}
					this.SendPropertyChanged("tbl_DatHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PayMeThod")]
	public partial class PayMeThod : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPay;
		
		private string _HinhThucThanhToan;
		
		private System.Nullable<bool> _Visible;
		
		private EntitySet<tbl_DatHang> _tbl_DatHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPayChanging(int value);
    partial void OnIdPayChanged();
    partial void OnHinhThucThanhToanChanging(string value);
    partial void OnHinhThucThanhToanChanged();
    partial void OnVisibleChanging(System.Nullable<bool> value);
    partial void OnVisibleChanged();
    #endregion
		
		public PayMeThod()
		{
			this._tbl_DatHangs = new EntitySet<tbl_DatHang>(new Action<tbl_DatHang>(this.attach_tbl_DatHangs), new Action<tbl_DatHang>(this.detach_tbl_DatHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPay", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPay
		{
			get
			{
				return this._IdPay;
			}
			set
			{
				if ((this._IdPay != value))
				{
					this.OnIdPayChanging(value);
					this.SendPropertyChanging();
					this._IdPay = value;
					this.SendPropertyChanged("IdPay");
					this.OnIdPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucThanhToan", DbType="NVarChar(50)")]
		public string HinhThucThanhToan
		{
			get
			{
				return this._HinhThucThanhToan;
			}
			set
			{
				if ((this._HinhThucThanhToan != value))
				{
					this.OnHinhThucThanhToanChanging(value);
					this.SendPropertyChanging();
					this._HinhThucThanhToan = value;
					this.SendPropertyChanged("HinhThucThanhToan");
					this.OnHinhThucThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit")]
		public System.Nullable<bool> Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this.OnVisibleChanging(value);
					this.SendPropertyChanging();
					this._Visible = value;
					this.SendPropertyChanged("Visible");
					this.OnVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PayMeThod_tbl_DatHang", Storage="_tbl_DatHangs", ThisKey="IdPay", OtherKey="IdPay")]
		public EntitySet<tbl_DatHang> tbl_DatHangs
		{
			get
			{
				return this._tbl_DatHangs;
			}
			set
			{
				this._tbl_DatHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_DatHangs(tbl_DatHang entity)
		{
			this.SendPropertyChanging();
			entity.PayMeThod = this;
		}
		
		private void detach_tbl_DatHangs(tbl_DatHang entity)
		{
			this.SendPropertyChanging();
			entity.PayMeThod = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.devvn_tinhthanhpho")]
	public partial class devvn_tinhthanhpho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matp;
		
		private string _name;
		
		private string _type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatpChanging(string value);
    partial void OnmatpChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public devvn_tinhthanhpho()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matp", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matp
		{
			get
			{
				return this._matp;
			}
			set
			{
				if ((this._matp != value))
				{
					this.OnmatpChanging(value);
					this.SendPropertyChanging();
					this._matp = value;
					this.SendPropertyChanged("matp");
					this.OnmatpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(100)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.devvn_quanhuyen")]
	public partial class devvn_quanhuyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maqh;
		
		private string _name;
		
		private string _type;
		
		private string _matp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaqhChanging(string value);
    partial void OnmaqhChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnmatpChanging(string value);
    partial void OnmatpChanged();
    #endregion
		
		public devvn_quanhuyen()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maqh", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maqh
		{
			get
			{
				return this._maqh;
			}
			set
			{
				if ((this._maqh != value))
				{
					this.OnmaqhChanging(value);
					this.SendPropertyChanging();
					this._maqh = value;
					this.SendPropertyChanged("maqh");
					this.OnmaqhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(30)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matp", DbType="VarChar(5)")]
		public string matp
		{
			get
			{
				return this._matp;
			}
			set
			{
				if ((this._matp != value))
				{
					this.OnmatpChanging(value);
					this.SendPropertyChanging();
					this._matp = value;
					this.SendPropertyChanged("matp");
					this.OnmatpChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
